### ISSUE TITLE
Query Regarding the Integration of Custom 3D Models with LucidDreamer's Gaussian Splatting Technique

### ISSUE THREAD

**Issue by yihong1120** [luciddreamer-cvlab/LucidDreamer#14]
Dear LucidDreamer Contributors,

I hope this message finds you well. I am reaching out to inquire about the possibility of integrating custom 3D models within the LucidDreamer framework, specifically in relation to the Gaussian splatting scenes generation process.

Having perused your impressive repository and the accompanying paper, I am intrigued by the potential applications of your domain-free generation technique. My interest lies in exploring how LucidDreamer might accommodate bespoke 3D models, which could be used in conjunction with the Gaussian splatting method to create unique and personalised scenes.

Would you be so kind as to provide guidance on whether the current implementation supports such an integration? If so, I would be most grateful for any documentation or examples that could assist me in understanding the process. Additionally, should this functionality not be present, might you consider it a worthwhile addition for future updates?

I am keen to experiment with LucidDreamer for an upcoming project that would greatly benefit from this capability. Your insights and advice would be invaluable in helping me to realise this endeavour.

Thank you for your time and the remarkable work you have shared with the community. I look forward to your response.

Best regards,
yihong1120

**Comment by ironjr** [comment]
Thank you for your acknowledgement and your intriguing idea. Our work is basically a Gaussian splatting generator, but as you may know, current (experimental) rendering pipelines integrate GS with other types of 3D models such as meshes. You can make use of the output `.ply` files from LucidDreamer and edit with various other types of software:

1. Super-splat: Web-based viewer / editor [https://playcanvas.com/super-splat](https://t.co/YEkNOC3ibt) by @playcanvas
2. [WebGL-based viewer](https://github.com/antimatter15/splat) by @antimatter15
3. [Unity engine plugin](https://github.com/keijiro/SplatVFX) by @keijiro
4. [Unreal engine plugin](https://akiya-research-institute.github.io/3dGaussiansPlugin-Manual/en/changelog/) by @Akiya-Research-Institute
5. [Spline Gaussian splatting support](https://twitter.com/splinetool)
6. [three.js integrated editor](https://lumalabs.ai/) from [Luma Labs AI](https://twitter.com/LumaLabsAI)

On the other hand, if you want our LucidDreamer to _receive_ inputs from 3D objects and existing scene, it could be extended by attaching a rendering pipeline at the _input_ of LucidDreamer.

I would like to note that we are very open to community contributions to improve upon this project. We admit that we do not know all the possible extensions of this project nor have the ability to implement them all. Please open any PR for the project if you have any good idea and we will be graciously integrating your contributions. Thank you.
