### ISSUE TITLE
Demo error in windows.

### ISSUE THREAD

**Issue by vdruts** [luciddreamer-cvlab/LucidDreamer#15]
(lucid) PS C:\Users\xxxx\Deep\LucidDreamer> CUDA_VISIBLE_DEVICES=0 python app.py
CUDA_VISIBLE_DEVICES=0 : The term 'CUDA_VISIBLE_DEVICES=0' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ CUDA_VISIBLE_DEVICES=0 python app.py
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CUDA_VISIBLE_DEVICES=0:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by esw0116** [comment]
Hello, 
Could you try using the command?: ``set CUDA_VISIBLE_DEVICES=0 & python run.py``
Also, it would be helpful for me to help you solve the problem if you tell us your running environment (Windows version, CUDA version (use command ``nvcc --version``), and your GPU model).

**Comment by esw0116** [comment]
Hello, 
Would you please use this command for running in Windows?
``set CUDA_VISIBLE_DEVICES=0 & python app.py``

**Comment by vdruts** [comment]
Thanks had to run them apart.

Not sure, why the downloads keep freezing for me. All my ports are open, firewall is off.

(lucid) PS C:\Users\xxxx\Deep\LucidDreamer> set CUDA_VISIBLE_DEVICES=0
(lucid) PS C:\Users\xxxx\Deep\LucidDreamer> python app.py
Fetching 10 files:  20%|█████████████                                                    | 2/10 [00:00<00:02,  3.37it/s]

**Comment by vdruts** [comment]
Stops at 20% each time...

**Comment by esw0116** [comment]
I have encountered same problem in Windows and solved it by adding ``local_dir_use_symlinks=False`` to ``snapshot_download`` function in HF.
Please change line [27](https://github.com/luciddreamer-cvlab/LucidDreamer/blob/1dc450a24e686de6a0293b90f74c163f18f09fee/app.py#L27)-42 to following python code:

```python
d = example_root
if len(glob.glob(os.path.join(d, '*.ply'))) < 8:
    snapshot_download(repo_id="ironjr/LucidDreamerDemo", repo_type="model", local_dir=d, local_dir_use_symlinks=False)

d = os.path.join(ckpt_root, 'Blazing Drive V11m')
if not os.path.exists(d):
    snapshot_download(repo_id="ironjr/BlazingDriveV11m", repo_type="model", local_dir=d, local_dir_use_symlinks=False)
d = os.path.join(ckpt_root, 'RealCartoon-Pixar V5')
if not os.path.exists(d):
    snapshot_download(repo_id="ironjr/RealCartoon-PixarV5", repo_type="model", local_dir=d, local_dir_use_symlinks=False)
d = os.path.join(ckpt_root, 'Realistic Vision V5.1')
if not os.path.exists(d):
    snapshot_download(repo_id="ironjr/RealisticVisionV5-1", repo_type="model", local_dir=d, local_dir_use_symlinks=False)
d = os.path.join(ckpt_root, 'SD1-5')
if not os.path.exists(d):
    snapshot_download(repo_id="runwayml/stable-diffusion-inpainting", repo_type="model", local_dir=d, local_dir_use_symlinks=False)
```
You will run gradio demo by using the modified code.

Meanwhile, I am looking for the reason why the downloading freezes without that option and will update the code to run gradio interfaces in any environments.
