### ISSUE TITLE
Build for Windows 

### ISSUE THREAD

**Issue by skaale** [luciddreamer-cvlab/LucidDreamer#2]
Will it be possible to build it for Windows

**Comment by aminesoulaymani** [comment]
[librairies.zip](https://github.com/luciddreamer-cvlab/LucidDreamer/files/13606353/librairies.zip)
@skaale I managed to compile it, I got those 2 .egg files to install (VS 2022, CUDA 11.8, WIN64, Python 3.10.6)

**Comment by ironjr** [comment]
Does it run well?

**Comment by aminesoulaymani** [comment]
> Does it run well?

@ironjr so far so good,  my poor geforce 3060 is struggling but no errors at sight. The compile process under windows went smooth even for me, I'm not an expert at all
![image](https://github.com/luciddreamer-cvlab/LucidDreamer/assets/29153520/10c449e0-e329-4644-993d-11c85a1b77fb)

**Comment by esw0116** [comment]
@aminesoulaymani
Good to hear the news. It seems like the model runs without any errors.
Please re-open the issue if you meet any trouble.
I will also check using your attachment in my Windows envrionment in a couple of days.

**Comment by vdruts** [comment]
How does one install a .egg file? It says it's deprecated.

(luciddreamer) PS C:\Users\xxxx\Deep\LucidDreamer\submodules> pip install .\simple_knn-0.0.0-py3.10-win-amd64.egg
ERROR: Invalid requirement: '.\\simple_knn-0.0.0-py3.10-win-amd64.egg'
Hint: It looks like a path. The path does exist.

Having a hard time installing this... Can't seem to install easy_install :/
