### ISSUE TITLE
No module named 'depth_diff_gaussian_rasterization_min'

### ISSUE THREAD

**Issue by tiandaoyuxi** [luciddreamer-cvlab/LucidDreamer#20]
(lucid) C:\DATA\LucidDreamer>python app.py
Traceback (most recent call last):
  File "C:\DATA\LucidDreamer\app.py", line 55, in <module>
    from luciddreamer import LucidDreamer
  File "C:\DATA\LucidDreamer\luciddreamer.py", line 41, in <module>
    from gaussian_renderer import render
  File "C:\DATA\LucidDreamer\gaussian_renderer\__init__.py", line 15, in <module>
    from depth_diff_gaussian_rasterization_min import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'depth_diff_gaussian_rasterization_min'

**Comment by tiandaoyuxi** [comment]
My OS is win 10

**Comment by tiandaoyuxi** [comment]
ok git pull

**Comment by esw0116** [comment]
Hello, have you solved the issue?

**Comment by tiandaoyuxi** [comment]
> Hello, have you solved the issue?

yes. git pull ,it's working.

**Comment by esw0116** [comment]
Great!

**Comment by j1ming999** [comment]
No module named 'depth_diff_gaussian_rasterization_min

**Comment by j1ming999** [comment]
how can i solve this problem？

**Comment by robot0321** [comment]
@j1ming999 current version has that module -- so please `git pull` if you do not update the codes

**Comment by Lifedecoder** [comment]
After `git pull,` error still occurs showing "No module named 'depth_diff_gaussian_rasterization_min'".
I've already set 'python setup.py install' in submodules/depth-diff-gaussian-rasterization-min. Does anybody know what's wrong?

**Comment by Lifedecoder** [comment]
Figure it out, it's due to the path of compiling results is different from my pip install path, move the compiled file into pip install path would be ok.
