### ISSUE TITLE
Error while runnin app.py

### ISSUE THREAD

**Issue by Mohamed2519** [luciddreamer-cvlab/LucidDreamer#27]
when i run `python app.py` this error and warning occurs
![Screenshot 2023-12-17 204027](https://github.com/luciddreamer-cvlab/LucidDreamer/assets/42303826/69c903e2-bf32-4455-855c-f99a70203ff6)

**Comment by esw0116** [comment]
Hello, I think you did not install the submodules in your environment.
Have you followed all the installation processes written in README.md?

**Comment by Mohamed2519** [comment]
i install all dependences, where did i find wheel files to install it?

**Comment by esw0116** [comment]
Actually, we deleted whl files since they cause another errors when running the code (occupying too much VRAM).
We have commented out import simple_knn and depth_diff_gaussian_rasterization_min in app.py.
Can you run app.py again after pulling the repository and report the error message?

**Comment by esw0116** [comment]
We closed the issue since there has been no reply for a few days.
Please reopen the issue if you face any problems.
