### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by mikeyimer** [luciddreamer-cvlab/LucidDreamer#30]
An error occurred during the generation process :
![捕获111](https://github.com/luciddreamer-cvlab/LucidDreamer/assets/137673481/91751f46-336f-47f1-aaf9-4b70a5c7a9b4)

**Comment by esw0116** [comment]
Hello, it seems that ``save_dir`` is not created before saving ply files.
We have updated the code to create directory if it does not exists.

**Comment by Asuiors** [comment]
there are other reasons for this error, In the 'luciddreamer.py' file, the 'save_dir' parameter of the 'LucidDreamer' class has a default value of None, and the save_dir is not passed when instantiating the LucidDreamer class in the app.py file, causing the program to run with the default value None, which causes the luciddreamer.py file to be executed to line 193
![image](https://github.com/luciddreamer-cvlab/LucidDreamer/assets/49892695/bfdd5014-b875-440b-989a-cc3f6be3070d)
. Trying to concatenate None with a string resulted in this error, which I avoided by changing the default value of the LucidDreamer class parameter save_dir to "./".
![image](https://github.com/luciddreamer-cvlab/LucidDreamer/assets/49892695/40feab8d-203c-487b-abef-dd129c81fd84)

**Comment by mikeyimer** [comment]
> there are other reasons for this error, In the 'luciddreamer.py' file, the 'save_dir' parameter of the 'LucidDreamer' class has a default value of None, and the save_dir is not passed when instantiating the LucidDreamer class in the app.py file, causing the program to run with the default value None, which causes the luciddreamer.py file to be executed to line 193 ![image](https://private-user-images.githubusercontent.com/49892695/292513749-bfdd5014-b875-440b-989a-cc3f6be3070d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjM1ODYsIm5iZiI6MTcwMzI2MzI4NiwicGF0aCI6Ii80OTg5MjY5NS8yOTI1MTM3NDktYmZkZDUwMTQtYjg3NS00NDBiLTk4OWEtY2MzZjZiZTMwNzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE2NDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOTNhMGM5NzdjNDU2NzI2MDFmZWI3MWMwYTJlYjMyMWIzYmNjNTQ5MGMzNjIwZWJjYTNkMWM4M2Q1YTMxNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DO0AvUSWRzf8rc9J_h-LJFGkh4WYGByLLgSaxlCA7mw) . Trying to concatenate None with a string resulted in this error, which I avoided by changing the default value of the LucidDreamer class parameter save_dir to "./". ![image](https://private-user-images.githubusercontent.com/49892695/292513882-40feab8d-203c-487b-abef-dd129c81fd84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjM1ODYsIm5iZiI6MTcwMzI2MzI4NiwicGF0aCI6Ii80OTg5MjY5NS8yOTI1MTM4ODItNDBmZWFiOGQtMjAzYy00ODdiLWFiZWYtZGQxMjljODFmZDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE2NDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYzViNjU4MGFmNGQxZjU5Zjc2Mzc3YTRiYzdlZTFmZWQwZDZlZmMyZGRhZDIzM2ZhYjlhZGNiNmNjYjcxYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pbbfqBGVkTqEm3u0shtd9bp_LGuzQZcwGwhQ_K-S_-M)

I modified it according to your instructions, but still got an error. Do I want to revert line 193 to before this version?
![捕获99](https://github.com/luciddreamer-cvlab/LucidDreamer/assets/137673481/0c12d8af-ce08-4a0d-90af-5cf42dbc501e)

**Comment by Asuiors** [comment]
> > there are other reasons for this error, In the 'luciddreamer.py' file, the 'save_dir' parameter of the 'LucidDreamer' class has a default value of None, and the save_dir is not passed when instantiating the LucidDreamer class in the app.py file, causing the program to run with the default value None, which causes the luciddreamer.py file to be executed to line 193 ![image](https://private-user-images.githubusercontent.com/49892695/292513749-bfdd5014-b875-440b-989a-cc3f6be3070d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjM1ODYsIm5iZiI6MTcwMzI2MzI4NiwicGF0aCI6Ii80OTg5MjY5NS8yOTI1MTM3NDktYmZkZDUwMTQtYjg3NS00NDBiLTk4OWEtY2MzZjZiZTMwNzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE2NDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOTNhMGM5NzdjNDU2NzI2MDFmZWI3MWMwYTJlYjMyMWIzYmNjNTQ5MGMzNjIwZWJjYTNkMWM4M2Q1YTMxNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DO0AvUSWRzf8rc9J_h-LJFGkh4WYGByLLgSaxlCA7mw) . Trying to concatenate None with a string resulted in this error, which I avoided by changing the default value of the LucidDreamer class parameter save_dir to "./". ![image](https://private-user-images.githubusercontent.com/49892695/292513882-40feab8d-203c-487b-abef-dd129c81fd84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjM1ODYsIm5iZiI6MTcwMzI2MzI4NiwicGF0aCI6Ii80OTg5MjY5NS8yOTI1MTM4ODItNDBmZWFiOGQtMjAzYy00ODdiLWFiZWYtZGQxMjljODFmZDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE2NDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYzViNjU4MGFmNGQxZjU5Zjc2Mzc3YTRiYzdlZTFmZWQwZDZlZmMyZGRhZDIzM2ZhYjlhZGNiNmNjYjcxYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pbbfqBGVkTqEm3u0shtd9bp_LGuzQZcwGwhQ_K-S_-M)
> 
> I modified it according to your instructions, but still got an error. Do I want to revert line 193 to before this version? ![捕获99](https://private-user-images.githubusercontent.com/137673481/292541305-0c12d8af-ce08-4a0d-90af-5cf42dbc501e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMDQ4MjEsIm5iZiI6MTcwMzMwNDUyMSwicGF0aCI6Ii8xMzc2NzM0ODEvMjkyNTQxMzA1LTBjMTJkOGFmLWNlMDgtNGEwZC05MGFmLTVjZjQyZGJjNTAxZS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QwNDA4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWJkYTViMWJhMGY0MDRmZmQ5ZjUzMzE4ZjA2NTRjYWE1N2JjOGUwODFkODE4MmUxZjc0MTY4NjgxNmQ3M2I1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iyRdsy25GAkhES5yw0dlykAwEt0hzsCrby9tWY_BnYE)

Please undo the change, line 193 is the place where the error is reported, not the cause of the error, I mean to change the
 def __init__(self, for_gradio=True, save_dir=None):
in line 59 of the luciddreamer.py file to 
def __init__(self, for_gradio=True, save_dir="./"):
![image](https://github.com/luciddreamer-cvlab/LucidDreamer/assets/49892695/d3b286d2-f0f8-4918-a099-9ac231c02279)

**Comment by esw0116** [comment]
Thanks to @mikeyimer and @Asuior  for pointing out the errors and the solutions.
We have updated app.py and app_mini.py to prevent the error.
