### ISSUE TITLE
ImportError when python run.py

### ISSUE THREAD

**Issue by hanhechong** [luciddreamer-cvlab/LucidDreamer#31]
The whole error is 

> ImportError: /home/hanhechong/anaconda3/envs/gaussian/lib/python3.7/site-packages/depth_diff_gaussian_rasterization_min-0.0.0-py3.7-linux-x86_64.egg/depth_diff_gaussian_rasterization_min/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops7resize_4callERKNS_6TensorEN3c108ArrayRefIlEENS5_8optionalINS5_12MemoryFormatEEE

I think that is due to the incorrect installation of the submodule depth-diff-gaussian-rasterization-min. So I install it once again. The only warning is the CUDA version is 11.6 while the version to compile Pytorch is 11.7, which does not influence the installation process. So what's the problem?
By the way, how to use pip to install these submodules as the system suggests this way.
Thank you! Any help will be appreciated.

**Comment by esw0116** [comment]
Hello, 
Unfortunately, I cannot pinpoint out the exact cause of the error since the error message has never been shown in my envorinment.
However, the message suggests that the python version of your environment is 3.7, which can cause compatibility errors.
Can you create a new environment with python version 3.9 and execute run.py?

**Comment by aleksaknezevic4** [comment]
I have the same problem:

```
Traceback (most recent call last):
  File "/mnt/storage/work/LucidDreamer/run.py", line 5, in <module>
    from luciddreamer import LucidDreamer
  File "/mnt/storage/work/LucidDreamer/luciddreamer.py", line 41, in <module>
    from gaussian_renderer import render
  File "/mnt/storage/work/LucidDreamer/gaussian_renderer/__init__.py", line 14, in <module>
    from depth_diff_gaussian_rasterization_min import GaussianRasterizationSettings, GaussianRasterizer
  File "/home/aleksa.knezevic/miniconda3/envs/lucid/lib/python3.9/site-packages/depth_diff_gaussian_rasterization_min-0.0.0-py3.9-linux-x86_64.egg/depth_diff_gaussian_rasterization_min/__init__.py", line 15, in <module>
    from . import _C
ImportError: /home/aleksa.knezevic/miniconda3/envs/lucid/lib/python3.9/site-packages/depth_diff_gaussian_rasterization_min-0.0.0-py3.9-linux-x86_64.egg/depth_diff_gaussian_rasterization_min/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN8BACKWARD6renderE4dim3S0_PK5uint2PKjiiPKfPK6float2PK6float4PK6float3S7_S7_S7_S7_S5_S7_S7_PSE_PSB_SH_PfSJ_
```

My torch version is: 2.1.1,
nvcc --version: Cuda compilation tools, release 11.8, V11.8.89
Driver Version: 545.23.08
