### ISSUE TITLE
The Transition vector of function generate_seed_hemisphere

### ISSUE THREAD

**Issue by jzh15** [luciddreamer-cvlab/LucidDreamer#34]
![QQ20240101-160209](https://github.com/luciddreamer-cvlab/LucidDreamer/assets/67944280/cadb7928-ac87-4bee-b5c4-18c4122b56f8)
Thank you very much for your work. This is a great project, but i have a question about the code.

Why did only the transition vector of the first pose change, while the rest remained at 0.

**Comment by robot0321** [comment]
Thank you for reporting the issue!
I guess we miss to test all the codes while we publish rapidly.
The error will be changed soon.
Thanks agian!
