### ISSUE TITLE
Colab notebook missing UI

### ISSUE THREAD

**Issue by brbbbq** [luciddreamer-cvlab/LucidDreamer#36]
I tried running the colab notebook from here:
https://colab.research.google.com/github/camenduru/LucidDreamer-Gaussian-colab/blob/main/LucidDreamer_Gaussian_colab.ipynb

But after the first cell completed running, there wasn't any UI. Is there supposed to be a gradio link or something?
![240103-134934-Screenshot](https://github.com/luciddreamer-cvlab/LucidDreamer/assets/135537138/01ee3a17-72d4-486d-a63c-c6a260f384f1)

**Comment by robot0321** [comment]
Sorry for the issue, but I guess the gradio will be run on the localhost:7860 (or pre-defined port).
If not, please ask @camenduru for that issue

**Comment by camenduru** [comment]
@brbbbq thanks for the info ❤ please try again
