### ISSUE TITLE
output

### ISSUE THREAD

**Issue by Tiandishihua** [luciddreamer-cvlab/LucidDreamer#4]
Can you get scene mesh output with texture colors?

**Comment by esw0116** [comment]
Hi,
I am sorry to say that we do not provide mesh type output.
Currently, Open3D supports some functions that convert point clouds into meshes (see [Open3D documentation page](http://www.open3d.org/docs/latest/tutorial/Advanced/surface_reconstruction.html)), but the results may not be satisfactory.
