### ISSUE TITLE
result

### ISSUE THREAD

**Issue by Tiandishihua** [luciddreamer-cvlab/LucidDreamer#5]
Can I get a 3D Gaussian point cloud for real-time rendering? If I just generate a short RGB video, what is the use of it?

**Comment by esw0116** [comment]
You can use your own save path using ``-s`` command after ``python run.py`` to save the Gaussian point cloud file.
In defaults, it is saved in ``outputs/{IMAGE_NAME}_{CAMPATH_GEN}_{SEED}/gsplat.ply`` folder.
You can use it to render with your own camera paths.
