### ISSUE TITLE
Error on HuggingFace

### ISSUE THREAD

**Issue by fasteinke** [luciddreamer-cvlab/LucidDreamer#6]
The HuggingFace demo just throws an error,  almost immediately when I try anything ... is there a problem here, or how I'm trying to use it?

**Comment by esw0116** [comment]
Thank you for letting us know. We have just noticed the error.
We are currently fixing the problem and inform you as soon as the demo runs without errors.

**Comment by ironjr** [comment]
Is the problem fixed? I have opened another (more compact) demo page here:
https://huggingface.co/spaces/ironjr/LucidDreamer-mini

There are more alternative options you can try LucidDreamer:
1. You can check out @camenduru's [Colab implementation](https://github.com/camenduru/LucidDreamer-Gaussian-colab).
2. You can clone this repository and run by `python run.py` with CLI support.
3. You can clone this repository and run by `python app_mini.py` with GUI support.

Please note that `python app.py` behaves exactly the save as the HF demo (without traffic-related problems), but it takes some time to download all the custom SD checkpoints for the demo. So, I suggest trying `python app_mini.py` first.

**Comment by camenduru** [comment]
@ironjr, we have 2 LucidDreamer 😋 https://github.com/camenduru/LucidDreamer-Gaussian-colab

**Comment by ironjr** [comment]
> @ironjr, we have 2 LucidDreamer 😋 https://github.com/camenduru/LucidDreamer-Gaussian-colab

Oh... Thanks for the correction! The other dreamer is also a great work, though 😆 I just edited the comment above

**Comment by fasteinke** [comment]
Thanks for sorting the issue  - worked fine ... although, terrible result - because of poor wording of the prompt, by me!
