### ISSUE TITLE
The output ply file does not have the color information, right?

### ISSUE THREAD

**Issue by Nikki29o** [luciddreamer-cvlab/LucidDreamer#8]
Hi,
The output ply file does not have the color information, right?
<img width="467" alt="image" src="https://github.com/luciddreamer-cvlab/LucidDreamer/assets/118735860/a6b99454-5344-4e41-818b-65faa85865fc">

**Comment by esw0116** [comment]
Hello, 
The output ply file has color information, but the format is different from typical point cloud, and the color information is not represented using MeshLab.
Try using SIBR viewers in [original Gaussian Splatting repo](https://github.com/graphdeco-inria/gaussian-splatting#interactive-viewers) to see the high-quality and colorized 3D scenes.

**Comment by ironjr** [comment]
You can quickly try this cool project in @playcanvas

https://playcanvas.com/super-splat

![image](https://github.com/luciddreamer-cvlab/LucidDreamer/assets/12259041/df9b6e05-d549-43b8-a3b1-818645833086)

Just drag and drop .PLY file to the web browser will do the job.

**Comment by Nikki29o** [comment]
Well received. Thanks!

Best wishes,
Yiran

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
